### ISSUE TITLE
global variables values are not being set while we use flows 

### ISSUE THREAD

**Issue by wajidkhanp** [postmanlabs/postman-flows#218]
I am using  Postman v9.9.3  client version and today I observed that global variables that are set in first request of the flows are not being updated and subsequent requests are failing due to this. 
Any work around solution which can help me here ? is this issue already reported ?

**Comment by dev-kanishk** [comment]
Hey In flows we are having a block by the name Create durables that can be used for persisting values across multiple connected blocks and inside the request block we have a configuration to set request variables that will be used when making the external API call for that particular block only.  

If this information didn't help can you share the screen shot of flow for better understanding.

**Comment by saswatds** [comment]
Hey @wajidkhanp We have tried explaining this behaviour in https://github.com/postmanlabs/postman-flows/discussions/142 . I recommend using Create Data (equivalent to local variable ) and Create Durable (equivalent to global variable) in flows instead of relying on Globals and Environment.
